### ISSUE TITLE
Interfaz de chat

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#105]
Crear interfaz de chat utilizando [HandlebarsJS](http://handlebarsjs.com/).
Hay que crear una capa donde mostrar los mensajes del chat, otra parte donde se vea con quién estamos hablando, una parte donde escribir, un botón para enviar mensajes y algún botón para insertar emoticonos (futura funcionalidad)

**Comment by ramako** [comment]
Hecho
