### ISSUE TITLE
Desarrollo de template

### ISSUE THREAD

**Issue by JCristobal** [iblancasa/BackendSI2-IV#52]
Issue para hablar sobre el desarrollo del template de la aplicación, en un principio habría que verse lo de [Bootstrap](http://getbootstrap.com/2.3.2/) y el diseño en general

[Enlace interesante](http://fortawesome.github.io/Font-Awesome/)

**Comment by JCristobal** [comment]
Fijate @rafaroc , he trabajado un poco con Bootstrap, acabo de subir una plantilla junto a la tuya en https://github.com/iblancasa/BackendSI2-IV/tree/master/vistacliente

Son un poco básicos y le faltan cosas, pero para empezar a trabajar están muy bien

**Comment by iblancasa** [comment]
Por favor, los templates van en "views".
Si no, es un follón auténtico

**Comment by JCristobal** [comment]
si, ahora mismo hay 2, ahora borro las sobrantes
