### ISSUE TITLE
Documentar código

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#71]
Recordad que hay que documentar el código.
Una ayudita puede ser utilizar [Smart Comments](http://smartcomments.github.io/). Si no entendéis cómo usarlo, hago una referencia en la Wiki.

**Comment by iblancasa** [comment]
[Este es el paquete del que ha hablado JJ hoy en clase](http://jashkenas.github.io/docco/)

**Comment by JCristobal** [comment]
Smart Comments no va bien con Mocha, los comento por mi cuenta, son funciones muy rebuscadas y es fácil que no se haya bibliotecas para esto



:squirrel:
