### ISSUE TITLE
Interfaz: Creación de plantilla simple

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#73]
Haría falta hacer una plantilla simple para varias cosas como "Políticas de privacidad" y cosas así, donde no es necesario un menú (estas cosas se rellenarían desde la configuración, no tenemos que llenarlas nosotros, tranquilos).

Os propongo algo como esto
![Boceto](http://fotos.subefotos.com/89ea6aaeaf30474426f78e904da1ebeco.jpg)

donde los dos rectángulos serían:
+ Superior: una imagen o texto donde ponga BackendSI2-IV
+ Inferior: el texto que sea

Utilizando bootstrap, para que toda la web tenga la misma apariencia.

**Comment by JCristobal** [comment]
Ya está subida, https://github.com/iblancasa/BackendSI2-IV/blob/master/app/views/basica.html , muy simplona, le faltan los colores, añadirle el logo y adaptarla a EJS, pero mañana cuando decidamos que estilo ponerle la pongo fina  :ok_hand:

:squirrel:
