### ISSUE TITLE
Lunes 12 de enero

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#75]
A las 8.30 hay DAI. Lo digo para que avancemos.

Cosas que avanzar:
+ @JCristobal [creo que la plantilla ya está acabada (la del panel de usuario) ¿verdad? En cuanto esté, se adapta al gestor de plantilas EJS.](https://github.com/iblancasa/BackendSI2-IV/issues/52). Lo siguiente a hacer en el campo de la vista es [la plantilla simple, que nos hará falta para la instalación](https://github.com/iblancasa/BackendSI2-IV/issues/73)
+ @ramako [¿está terminada la referencia de Mongoose?](https://github.com/iblancasa/BackendSI2-IV/issues/56) Cuando esté, habrá que ponerse con la "instalación tipo Wordpress" que te comenté para tener disponibles todas las estructuras de datos.

Cuando esté la interfaz y esté acabada la instalación, el siguiente paso es empezar a implementar operaciones.

Venga chicos, queda poco.

**Comment by ramako** [comment]
La referencia de Mongoose está practicamente acabada. Creo que lo necesario y lo que vamos a usar está cubierto. Solo me faltaria revisarla y comprobar que esta todo correcto.

En cuanto a DAI, opino por usar también las 2 horas de IV que tenemos justo después, que uno de nosotros vaya a IV para enterarse de lo que dice el profesor con respecto a las prácticas y los ejercicios y cuando se haya enterado que vuelva para seguir trabajando en el proyecto.

**Comment by iblancasa** [comment]
Sí, yo tenía pensado hacer eso.
Yo bajo a hablar con el profesor :D

**Comment by JCristobal** [comment]
La plantilla que está subida si, sólo falta pequeños retoques y cambiarle los textos a algunos campos.
La plantilla simpre la tengo que hacer, si no la tengo para mañana en un rato la hago... he estado atareado con el guante jajaja

Nos vemos mañana por la mañana pues! :squirrel: :squirrel:
