### ISSUE TITLE
Arreglar desastre

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#76]
Pues ya sabéis..

**Comment by rafaroc** [comment]
K a pasado?

**Comment by iblancasa** [comment]
[Respuesta](https://docs.google.com/spreadsheets/d/1f0p1Fc7BsXp2lz0E3Ow8w6FymujwBtQq6dCxoecxX7M/edit#gid=0)

**Comment by JCristobal** [comment]
@rafaroc respondo a tu [comentario](https://github.com/iblancasa/BackendSI2-IV/issues/77#issuecomment-69545274) hemos hablado con el profesor, dice que trabajemos con una rama sólo y vamos a usar Openshift en vez de Heroku. Ahora mismo estamos viendo eso.

**Comment by rafaroc** [comment]
Vale lo k OS e dixo si kereis OS paso mi num de móvil y acemos un grupo de
was app hablamos x ay k es mas rápido  aora mismo estoy probando lo del
script de isntallar docker el docker file ese k a dixo israel
