### ISSUE TITLE
Nos mudamos a Openshift

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#77]
Nos vamos de Heroku para simplificar cosas (conexión BD)... espero.

**Comment by rafaroc** [comment]
eeii no e podido ir a la facultad que etengo el calentador roto y estan arreglandolo ahora decirme que hay que hacer y me pongo ahora desde mi casa si quereis os dejo mi num de mvl y hacemos un grupo y hablamos x ay que es mas rapido que por aqui
