### ISSUE TITLE
Añadir licencia

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#78]
No teníamos licencia puesta... :cold_sweat:
¿GPL V2 o MIT?

**Comment by JCristobal** [comment]
No entiendo mucho de licencias ... pero GPL V2 es algo más restrictiva no?
Si fuera así yo diría esa  :grin:

**Comment by iblancasa** [comment]
¿Por qué la más restrictiva?

Salvo que me equivoque... GPL hace que todo lo que componga el software debe ser software libre. La otra es compatible con privativo

**Comment by JCristobal** [comment]
Lo he leido en un par de comentarios, pero desde la ignorancia lo digo jajaj

Pues no sabría que enfoque darle, según como lo quiera enfocar Ángel y la empresa

**Comment by iblancasa** [comment]
Vamos a ponerle MIT... Se usa mucho y es la que yo uso cuando eso
