### ISSUE TITLE
Integración continua

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#82]
Yo pensaba que ya teníamos con el Docker.. pero parece que no...

**Comment by iblancasa** [comment]
Los test que tenemos valen, pero vamos a hacerlo con travis (usando esos mismos test).
Dejo un pequeño tutorial
[Tutorial](https://medium.com/@_jh3y/getting-started-with-mocha-bfa20d403186)

**Comment by ramako** [comment]
También existe Jenkins, que tiene interfaz web.

Aquí esta el tutorial:
http://johnhamelink.com/testing-nodejs-with-jenkins.html

**Comment by ramako** [comment]
Para travis se necesita que el que tenga el repositorio (es decir @iblancasa ) se conecte a travis (se logea a traves de github) y active el boton para el repositorio para que haga los test.

**Comment by iblancasa** [comment]
@ramako , cuando hagas un commit referente a un issue, como el que acabas de hacer, añade la referencia al issue que se está intentando solucionar (recomendación hoy del profesor)
Voy a hacer lo que dices

**Comment by iblancasa** [comment]
[Aquí tenéis](https://travis-ci.org/iblancasa/BackendSI2-IV)

**Comment by iblancasa** [comment]
Hay una cosa que no comprendo bien. [Según esta web](http://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/) (nos será útil pronto):
"When updates are made to your repository, a POST request is sent to this URL, which notifies your Azure Website that the repository has been updated. At this point it retrieves the update and deploys it to your website."

Entiendo que esa petición "POST" no se hace hasta que los test no han sido pasados... ¿no?

**Comment by iblancasa** [comment]
Ya se ha hecho una "build". Hay un problema en el fichero travis.
Para no liar mucho follón, mirad [esta web](http://docs.travis-ci.com/user/getting-started/) donde podréis ver una sección que pone "validate travis". Instalando una gema, se puede comprobar si el fichero está bien o no :dancer:

**Comment by ramako** [comment]
Perfecto! gracias

**Comment by ramako** [comment]
El problema parece ser que era en el makefile que era espacios y no un tab. Pero para comprobar el makefile creo que esa web no sirve, solo para el fichero yml.

Si para comprobar que funciona hay que hacer commits...menudo follon.

**Comment by iblancasa** [comment]
Los test puedo ejecutarlos yo sin que sea necesario hacer un commit. Pero claro, hará falta hacer el commit para subir el fichero...

**Comment by iblancasa** [comment]
Jenkins lo acabo de probar. Travis es lo que tenemos que usar. De verdad. No lo intentéis con lo otro. He visto cosas horribles

**Comment by iblancasa** [comment]
[Ya tenemos integración.](https://travis-ci.org/iblancasa/BackendSI2-IV/builds/46918005) En cuanto se pasen los test, cerramos el issue

**Comment by iblancasa** [comment]
Además, tendré que hacer [esto](http://thewebivore.com/continuously-deploying-free-openshift-site-travis-ci/). Digo tendré, por que la aplicación de Heroku está a mi nombre.

Supongo que así se hará también para Azure.

**Comment by ramako** [comment]
Excelente, ahora si funciona. De hecho cada vez que hagamos un commit se va a hacer la build por lo que he visto.

**Comment by iblancasa** [comment]
Claro. Cuando lo enganchemos con Azure y/OpenShift, una vez hecho un
commit, hace los test y, si se pasan, lo envía al PaaS o IaaS
