### ISSUE TITLE
Despliegue usando Ansible o similares

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/BackendSI2-IV#84]
Yo creo que lo suyo es Ansible.
En los ejercicios de clase se hace con Azure, por lo que creo que deberíamos hacerlo así

**Comment by ramako** [comment]
Yo también, como extra podríamos probar con Cheff, que supongo que aumentará la nota global de todo el grupo el haberlo hecho de dos formas distintas. Claro que, digo esto, pero todavía no he toqueteado Cheff, lo mismo es acabar desquiciado...

**Comment by iblancasa** [comment]
No lo sé...
Empecemos por hacerlo y luego los extras jajaja

**Comment by iblancasa** [comment]
Ya se cómo hacerlo :D Le vamos a meter hasta dibujos mientras se despliega :punch::punch::punch::punch::punch::punch:

**Comment by JCristobal** [comment]
_
     /(|
    (  :
   __\  \  _____
 (____)  `|
(____)|   |
 (____).__|
  (___)__.|_____

Ese Travis como mola

**Comment by iblancasa** [comment]
Si echáis un ojo al fichero [Travis](https://github.com/iblancasa/BackendSI2-IV/blob/master/.travis.yml), veréis que, después de ejecutarse los test, se ejecutan unos scripts.

Esos scripts son los que deberán ejecutar el despliegue en Azure

**Comment by iblancasa** [comment]
Creo que se hace [así](https://cowbell-labs.com/2014-03-06-capistrano-deploys-from-travis.html)

**Comment by iblancasa** [comment]
[Enlace importante sobre SSH y Ansible](http://www.hashbangcode.com/blog/ansible-ssh-setup-playbook)

**Comment by ramako** [comment]
## Crear Playbook Ansible solo para despliegues

¿La diferencia con el que tenemos cuál es? ¿Tenía que coger algún fichero del travis?

**Comment by iblancasa** [comment]
No.
El que tenemos provisiona y despliega. El que hay que crear, solo tiene que
desplegar )y será el que ejecute Travis)

**Comment by ramako** [comment]
He estado tocando el travis.yml (como habreis podido comprobar en vuestros mails) para instalar python y ansible y , extrañamente, peta en los tests diciendo que no encuentra mocha.
Habia añadido estas lineas después de node_js y antes de before_script.
```
before_install:
  - sudo apt-get install -qq python
install:
  - sudo pip install ansible
```

Luego más tarde seguiré intentandolo....

**Comment by iblancasa** [comment]
Tranquilidad. ¿Qué hace la opción ``-qq``?

**Comment by iblancasa** [comment]
Arreglado.
La he liado un poco, pero ya funciona todo.

Cuando teníamos el fichero "make", se estaba llamando al "Mocha" que se instala en el directorio "npm_modules". Cuando eliminamos ese fichero, estábamos llamando a Mocha instalado en el sistema (el que se instala con ``sudo npm install -g mocha``). Por alguna extraña razón, algunos builds han funcionado bien sin arreglar ese problema...

Tampoco podía instalar Mocha de forma global en Travis (tal vez lo traiga instalado y se haya creado algún conflicto).



[El build](https://travis-ci.org/iblancasa/BackendSI2-IV/builds/48168154)

**Comment by ramako** [comment]
Perfecto! Ya he echado un vistazo a los ficheros actualizados.

**Comment by iblancasa** [comment]
Funciona todo a mano. Falta que lo haga Travis.

**Comment by iblancasa** [comment]
Hace falta hacer un script que instale:
+ Python
+ Ansible
+ sshpass
+ Ejecute el playbook de despliegue

y otro que haga lo mismo pero al final ejecute el de aprovisionamiento

**Comment by iblancasa** [comment]
Ahora el fichero del servicio se genera en tiempo de ejecución.
Esa generación hay que hacerla en el script de aprovisionamiento, no en el de despliegue.

**Comment by iblancasa** [comment]
Hay un pequeño problema:
cuando se lanza la aplicación, Ansible se queda colgado.
Haciendo "control+C", se corta la ejecución, pero el Backend sigue funcionando.

En Travis pasa parecido. Si detenemos la ejecución, [nos muestra que todo ha ido bien](https://travis-ci.org/iblancasa/BackendSI2-IV/builds/48972389).

No creo que sea un problema.

**Comment by iblancasa** [comment]
Si siguen haciendo falta hacer los scripts que comento un poco más arriba.

**Comment by iblancasa** [comment]
He estado intentando que no se quede pillado dejando en background la ejecución pero... no lo he conseguido.
Voy a probar otras cosas luego

**Comment by ramako** [comment]
¿El script no lo habiamos hecho ya en el fichero travis?

**Comment by iblancasa** [comment]
Es parecido. De hecho para despliegue se puede usar el mismo de Travis (pero sin generar el servicio, eso hay que moverlo al de aprovisionamiento)
Es para poder ejecutarlo desde tu PC.
Aprovisionamiento solo se aprovisiona una vez.

**Comment by iblancasa** [comment]
Si no me explico no os preocupéis, luego en un momento lo hago yo. Es una tontería, pero es para que quede mejor.

Creo que ya se cómo hacer para que no que quede pillado el despliegue. De todas formas, lo único que pasa al quedarse pillado es que Travis se queda esperando.
Si Travis después de un tiempo "corta" el comando, todo va OK

**Comment by iblancasa** [comment]
Pero que no es nada grave por que los tests se pasan y se despliega bien

**Comment by iblancasa** [comment]
Ya no se queda pillado :D

**Comment by ramako** [comment]
¿Siguen haciendo falta los scripts?

**Comment by JCristobal** [comment]
si, lo que ha hecho @iblancasa es arreglar el bloqueo que había

(no se como has caido en arregrarlo :confused:)

**Comment by iblancasa** [comment]
El arreglo ha sido decirle a Ansible que es una tarea asíncrona y que no la
espere
