### ISSUE TITLE
Devolver consultas para la web (BDD)

### ISSUE THREAD

**Issue by ramako** [iblancasa/BackendSI2-IV#89]
@iblancasa 
He subido un empresa.js en el que, supuestamente, muestra todas las empresas que hay en la base de datos almacenada.

Para mostrar la consulta en node creo que seria algo así
```javascript
var consultaWebEmpresas = require('../model/empresa.js');
consultaWebEmpresas.listaEmpresas(function(err,empresas){

mostrarEmpresas= empresas
```
donde los datos de la consulta son devueltos en function(err,empresas) , estando los datos (el json supongo) en la variable empresas.

Pero esto hay que probarlo (y arreglarlo, porque dudo que funcione a la primera).

**Comment by iblancasa** [comment]
>Pero esto hay que probarlo (y arreglarlo, porque dudo que funcione a la primera).

¡Así, con positividad!

Mañana lo probamos. Voy a actualizar el TODO para poner lo mínimo, mínimo que deberíamos hacer
