### ISSUE TITLE
Documentación.

### ISSUE THREAD

**Issue by ramako** [iblancasa/BackendSI2-IV#91]
¡Espero que esta semana de exámenes no haya sido demasiado dura con vosotros!
Un recordatorio algo off topic antes de ir al tema de este issue, tenemos que elegir fecha y hora de presentación (creo que todavia no la hemos elegido).

Recordad que la documentación ha de ir en el README.md , y que tenemos que participar TODOS en ella para optar a:

*2 puntos: documentación en línea y externa correcta*

Deberiamos organizarnos sobre cómo y qué va a documentar cada uno (y para eso he abierto este issue). Así pues, ¡debatamos!

**Comment by iblancasa** [comment]
Puntos a documentar:
+ Por qué Openshift
+ Por qué Azure
+ Cómo se ejecuta la aplicación (comandos)
+ Cómo se ejecutan los test (comandos)
+ Cómo se realiza la integración continua (contar que los test van a Travis, se ejecutan, dónde y cómo se despliega)

En este último punto entra explicar que se usa Ansible, por qué y qué hacer para ejecutar las recetas

**Comment by ramako** [comment]
Bueno, para no abusar mucho me pido los tests, luego cuando se vayan eligiendo más me asigno otro (si fuera necesario que supongo que si).

**Comment by JCristobal** [comment]
Yo estoy haciendo la parte de OpenShift, cuando acabe la subo y vamos viendo

**Comment by iblancasa** [comment]
¿ @JCristobal  Pero por qué lo creas en la Wiki?

A ver qué es lo que escribís de cada cosa...

**Comment by ramako** [comment]
@iblancasa He escrito algo de los tests, no sé si seguir ese estilo en la documentación o hay alguna alternativa mejor, echale un vistazo cuando puedas (README.md, al final del todo) y comentas por aqui.

**Comment by iblancasa** [comment]
@ramako , has empezado bien pero después no.
Hay que explicar qué bibliotecas usamos (Mocha, Chai, Supertest), para qué cada una y por qué hemos elegido esas y no otras. Además, cómo se ejecutan los test. En nuestro caso, esto último es con

```bash
npm test
```

Go go :dizzy:

**Comment by ramako** [comment]
¡Ok!

**Comment by iblancasa** [comment]
Falta:
* Cómo se realiza la integración continua (contar que los test van a Travis, se ejecutan, dónde y cómo se despliega)
* Por qué hemos utilizado Docker y cómo se echa a andar Docker (tenemos un script por ahí que hace todo, solo habría que ejecutarlo y, dentro de la máquina, hacer algunas cosas como las de la sección que acabo de añadir de "Cómo ejecutar")

y creo que ya..

**Comment by iblancasa** [comment]
Falta hablar de aprovisonamiento.

+ Por qué Ansible
+ Cómo hacer aprovisionamiento (ejecución de script)

**Comment by ramako** [comment]
Me adjudico por qué ansible (si nadie lo esta haciendo nada) y si no os importa.

**Comment by iblancasa** [comment]
Vale
